export const names = [
  { name:"澁谷 信也",nameKana:"シブヤ シンヤ",lastName:"澁谷",firstName:"信也",lastNameKana:"シブヤ",firstNameKana:"シンヤ",sex: 0},
  { name:"駒井 智",nameKana:"コマイ サトル",lastName:"駒井",firstName:" 智",lastNameKana:"コマイ",firstNameKana:"サトル",sex: 0},
  { name:"高塚 崇史",nameKana:"タカツカ  タカシ",lastName:"高塚",firstName:"崇史",lastNameKana:"タカツカ",firstNameKana:" タカシ",sex: 0},
  { name:"弘田 正文",nameKana:"ヒロタ サフミ",lastName:"弘田",firstName:"正文",lastNameKana:"ヒロタ",firstNameKana:"サフミ",sex: 0},
  { name:"田北 秀則",nameKana:"タキタ デノリ",lastName:"田北",firstName:"秀則",lastNameKana:"タキタ",firstNameKana:"デノリ",sex: 0},
  { name:"池畑 昌明",nameKana:"イケハタ マサアキ",lastName:"池畑",firstName:"昌明",lastNameKana:"イケハタ",firstNameKana:"マサアキ",sex: 0},
  { name:"鷲田 至",nameKana:"ワシダ イタル",lastName:"鷲田",firstName:" 至",lastNameKana:"ワシダ",firstNameKana:"イタル",sex: 0},
  { name:"五十川 文昭",nameKana:"イソガワ フミアキ",lastName:"五十川",firstName:" 文昭",lastNameKana:"イソガワ",firstNameKana:"フミアキ",sex: 0},
  { name:"洞口 一生",nameKana:"ホラグチ  カズオ",lastName:"洞口",firstName:"一生",lastNameKana:"ホラグチ",firstNameKana:" カズオ",sex: 0},
  { name:"坂爪 雅巳",nameKana:"サカヅメ  マサミ",lastName:"坂爪",firstName:"雅巳",lastNameKana:"サカヅメ",firstNameKana:" マサミ",sex: 0},
  { name:"徳富 善博",nameKana:"トクトミ ヨシヒロ",lastName:"徳富",firstName:"善博",lastNameKana:"トクトミ",firstNameKana:"ヨシヒロ",sex: 0},
  { name:"横村 広宣",nameKana:"ヨコムラ ヒロノブ",lastName:"横村",firstName:"広宣",lastNameKana:"ヨコムラ",firstNameKana:"ヒロノブ",sex: 0},
  { name:"常田 晴雄",nameKana:"ツネダ ハルオ",lastName:"常田",firstName:"晴雄",lastNameKana:"ツネダ",firstNameKana:"ハルオ",sex: 0},
  { name:"種本 正士",nameKana:"タネモト  マサシ",lastName:"種本",firstName:"正士",lastNameKana:"タネモト",firstNameKana:" マサシ",sex: 0},
  { name:"湊谷 浩志",nameKana:"ミナトヤ  コウジ",lastName:"湊谷",firstName:"浩志",lastNameKana:"ミナトヤ",firstNameKana:" コウジ",sex: 0},
  { name:"岡垣 雅嗣",nameKana:"オカガキ マサツグ",lastName:"岡垣",firstName:"雅嗣",lastNameKana:"オカガキ",firstNameKana:"マサツグ",sex: 0},
  { name:"依藤 昌大",nameKana:"ヨリフジ マサヒロ",lastName:"依藤",firstName:"昌大",lastNameKana:"ヨリフジ",firstNameKana:"マサヒロ",sex: 0},
  { name:"前澤 慧太",nameKana:"マエサワ  ケイタ",lastName:"前澤",firstName:"慧太",lastNameKana:"マエサワ",firstNameKana:" ケイタ",sex: 0},
  { name:"内林 大将",nameKana:"ウチバヤシ  ヒロマサ",lastName:"内林",firstName:"大将",lastNameKana:"ウチバヤシ",firstNameKana:" ヒロマサ",sex: 0},
  { name:"稲野辺 功一郎",nameKana:"イナノベ イチロウ",lastName:"稲野辺",firstName:"功一郎",lastNameKana:"イナノベ",firstNameKana:"イチロウ",sex: 0},
  { name:"桂 正泰",nameKana:"ケイ ヤス",lastName:"桂",firstName:"泰",lastNameKana:"ケイ",firstNameKana:"ヤス",sex: 0},
  { name:"野並 健二朗",nameKana:"ノナミ ジロウ",lastName:"野並",firstName:"二朗",lastNameKana:"ノナミ",firstNameKana:"ジロウ",sex: 0},
  { name:"宮重 眞澄",nameKana:"ミヤシゲ  マスミ",lastName:"宮重",firstName:"眞澄",lastNameKana:"ミヤシゲ",firstNameKana:" マスミ",sex: 0},
  { name:"島原 茂弘",nameKana:"シマバラ シゲヒロ",lastName:"島原",firstName:"茂弘",lastNameKana:"シマバラ",firstNameKana:"シゲヒロ",sex: 0},
  { name:"戦 將人",nameKana:"セン サト",lastName:"戦",firstName:"人",lastNameKana:"セン",firstNameKana:"サト",sex: 0},
  { name:"玄番 政洋",nameKana:"ゲンバ サヒロ",lastName:"玄番",firstName:"政洋",lastNameKana:"ゲンバ",firstNameKana:"サヒロ",sex: 0},
  { name:"向谷 大裕",nameKana:"ムカイダニ  ダイスケ",lastName:"向谷",firstName:"大裕",lastNameKana:"ムカイダニ",firstNameKana:" ダイスケ",sex: 0},
  { name:"宇土 龍三",nameKana:"ウド ゾウ",lastName:"宇土",firstName:"龍三",lastNameKana:"ウド",firstNameKana:"ゾウ",sex: 0},
  { name:"福王寺 益弘",nameKana:"フクオウジ  マスヒロ",lastName:"福王寺",firstName:" 益弘",lastNameKana:"フクオウジ",firstNameKana:" マスヒロ",sex: 0},
  { name:"矢埜 滉太",nameKana:"ヤノ ウタ",lastName:"矢埜",firstName:"滉太",lastNameKana:"ヤノ",firstNameKana:"ウタ",sex: 0},
  { name:"小野塚 淳史",nameKana:"オノツカ ジュンジ",lastName:"小野塚",firstName:" 淳史",lastNameKana:"オノツカ",firstNameKana:"ジュンジ",sex: 0},
  { name:"掛布 喜幸",nameKana:"カケノ シユキ",lastName:"掛布",firstName:"喜幸",lastNameKana:"カケノ",firstNameKana:"シユキ",sex: 0},
  { name:"夏苅 連",nameKana:"ナツガリ リ レン",lastName:"夏苅",firstName:" 連",lastNameKana:"ナツガリ",firstNameKana:"リ レン",sex: 0},
  { name:"舛谷 恒一郎",nameKana:"マスタニ イチロウ",lastName:"舛谷",firstName:"一郎",lastNameKana:"マスタニ",firstNameKana:"イチロウ",sex: 0},
  { name:"伊良原 剣",nameKana:"イラハラ  ツルギ",lastName:"伊良原",firstName:"原 剣",lastNameKana:"イラハラ",firstNameKana:" ツルギ",sex: 0},
  { name:"天明 穣二",nameKana:"テンメイ ジョウジ",lastName:"天明",firstName:"穣二",lastNameKana:"テンメイ",firstNameKana:"ジョウジ",sex: 0},
  { name:"埴田 秀策",nameKana:"ハニダ ウサク",lastName:"埴田",firstName:"秀策",lastNameKana:"ハニダ",firstNameKana:"ウサク",sex: 0},
  { name:"諸我 奨",nameKana:"モロガ タスク",lastName:"諸我",firstName:" 奨",lastNameKana:"モロガ",firstNameKana:"タスク",sex: 0},
  { name:"棈木 雄市",nameKana:"アベキ ウイチ",lastName:"棈木",firstName:"雄市",lastNameKana:"アベキ",firstNameKana:"ウイチ",sex: 0},
  { name:"日川 佳人",nameKana:"ヒカワ ヨシト",lastName:"日川",firstName:"佳人",lastNameKana:"ヒカワ",firstNameKana:"ヨシト",sex: 0},
  { name:"坂宮 研悟",nameKana:"サカミヤ  ケンゴ",lastName:"坂宮",firstName:"研悟",lastNameKana:"サカミヤ",firstNameKana:" ケンゴ",sex: 0},
  { name:"溝添 国弘",nameKana:"ミゾゾエ クニヒロ",lastName:"溝添",firstName:"国弘",lastNameKana:"ミゾゾエ",firstNameKana:"クニヒロ",sex: 0},
  { name:"葭田 靖成",nameKana:"ヨシタ スナリ",lastName:"葭田",firstName:"靖成",lastNameKana:"ヨシタ",firstNameKana:"スナリ",sex: 0},
  { name:"新乃 勝吉",nameKana:"シンノ ツヨシ",lastName:"新乃",firstName:"勝吉",lastNameKana:"シンノ",firstNameKana:"ツヨシ",sex: 0},
  { name:"小勝負 研史",nameKana:"コショウブ ブ ケンジ",lastName:"小勝負",firstName:" 研史",lastNameKana:"コショウブ",firstNameKana:"ブ ケンジ",sex: 0},
  { name:"髙岩 崇志",nameKana:"タカイワ タカユキ",lastName:"髙岩",firstName:"崇志",lastNameKana:"タカイワ",firstNameKana:"タカユキ",sex: 0},
  { name:"増毛 秀克",nameKana:"マスモ デカツ",lastName:"増毛",firstName:"秀克",lastNameKana:"マスモ",firstNameKana:"デカツ",sex: 0},
  { name:"黒堀 光祥",nameKana:"クロホリ ミツヨシ",lastName:"黒堀",firstName:"光祥",lastNameKana:"クロホリ",firstNameKana:"ミツヨシ",sex: 0},
  { name:"駄木 知克",nameKana:"ダキ カツ",lastName:"駄木",firstName:"知克",lastNameKana:"ダキ",firstNameKana:"カツ",sex: 0},
  { name:"髑髏林 剛士",nameKana:"ドクロバヤシ ヤシ ゴウシ",lastName:"髑髏林",firstName:" 剛士",lastNameKana:"ドクロバヤシ",firstNameKana:"ヤシ ゴウシ",sex: 0},
  { name:"小鴨 黒",nameKana:"コガモ  クロ",lastName:"小鴨",firstName:" 黒",lastNameKana:"コガモ",firstNameKana:" クロ",sex: 0},
  { name:"丹慶 広孝",nameKana:"タンケイ ヒロタカ",lastName:"丹慶",firstName:"広孝",lastNameKana:"タンケイ",firstNameKana:"ヒロタカ",sex: 0},
  { name:"宅瀬 学人",nameKana:"タクセ マナト",lastName:"宅瀬",firstName:"学人",lastNameKana:"タクセ",firstNameKana:"マナト",sex: 0},
  { name:"奈津 長門",nameKana:"ナツ ガト",lastName:"奈津",firstName:"長門",lastNameKana:"ナツ",firstNameKana:"ガト",sex: 0},
  { name:"入梅 倫正",nameKana:"イリウメ ミチマサ",lastName:"入梅",firstName:"倫正",lastNameKana:"イリウメ",firstNameKana:"ミチマサ",sex: 0},
  { name:"白根澤 信基",nameKana:"シラネザワ ワ ノブキ",lastName:"白根澤",firstName:" 信基",lastNameKana:"シラネザワ",firstNameKana:"ワ ノブキ",sex: 0},
  { name:"新改 恵理也",nameKana:"シンガイ  エリヤ",lastName:"新改",firstName:"理也",lastNameKana:"シンガイ",firstNameKana:" エリヤ",sex: 0},
  { name:"崎花 崇成",nameKana:"サキハナ タカナリ",lastName:"崎花",firstName:"崇成",lastNameKana:"サキハナ",firstNameKana:"タカナリ",sex: 0},
  { name:"湯倉 永悟",nameKana:"ユクラ エイゴ",lastName:"湯倉",firstName:"永悟",lastNameKana:"ユクラ",firstNameKana:"エイゴ",sex: 0},
  { name:"家治川 巡",nameKana:"カジカワ  メグル",lastName:"家治川",firstName:"川 巡",lastNameKana:"カジカワ",firstNameKana:" メグル",sex: 0},
  { name:"本多 真由",nameKana:"ホンダ  マユ",lastName:"本多",firstName:"真由",lastNameKana:"ホンダ",firstNameKana:" マユ",sex: 1},
  { name:"藤沢 優香",nameKana:"フジサワ  ユウカ",lastName:"藤沢",firstName:"優香",lastNameKana:"フジサワ",firstNameKana:" ユウカ",sex: 1},
  { name:"古井 昭子",nameKana:"フルイ アキコ",lastName:"古井",firstName:"昭子",lastNameKana:"フルイ",firstNameKana:"アキコ",sex: 1},
  { name:"小濱 歩実",nameKana:"コハマ アユミ",lastName:"小濱",firstName:"歩実",lastNameKana:"コハマ",firstNameKana:"アユミ",sex: 1},
  { name:"江森 政子",nameKana:"エモリ マサコ",lastName:"江森",firstName:"政子",lastNameKana:"エモリ",firstNameKana:"マサコ",sex: 1},
  { name:"白倉 千智",nameKana:"シラクラ  チサト",lastName:"白倉",firstName:"千智",lastNameKana:"シラクラ",firstNameKana:" チサト",sex: 1},
  { name:"茂木 紗央里",nameKana:"モテキ サオリ",lastName:"茂木",firstName:"央里",lastNameKana:"モテキ",firstNameKana:"サオリ",sex: 1},
  { name:"牧村 和香奈",nameKana:"マキムラ  ワカナ",lastName:"牧村",firstName:"香奈",lastNameKana:"マキムラ",firstNameKana:" ワカナ",sex: 1},
  { name:"伊崎 栄",nameKana:"イザキ サカエ",lastName:"伊崎",firstName:" 栄",lastNameKana:"イザキ",firstNameKana:"サカエ",sex: 1},
  { name:"岩脇 朋枝",nameKana:"イワワキ  トモエ",lastName:"岩脇",firstName:"朋枝",lastNameKana:"イワワキ",firstNameKana:" トモエ",sex: 1},
  { name:"天木 早代",nameKana:"アマキ  サヨ",lastName:"天木",firstName:"早代",lastNameKana:"アマキ",firstNameKana:" サヨ",sex: 1},
  { name:"古泉 涼香",nameKana:"コイズミ リョウカ",lastName:"古泉",firstName:"涼香",lastNameKana:"コイズミ",firstNameKana:"リョウカ",sex: 1},
  { name:"中司 カナ",nameKana:"ナカツカサ カサ カナ",lastName:"中司",firstName:"カナ",lastNameKana:"ナカツカサ",firstNameKana:"カサ カナ",sex: 1},
  { name:"高阪 きよ子",nameKana:"コウサカ  キヨコ",lastName:"高阪",firstName:"よ子",lastNameKana:"コウサカ",firstNameKana:" キヨコ",sex: 1},
  { name:"冠 美好",nameKana:"カンムリ  ミヨシ",lastName:"冠",firstName:"好",lastNameKana:"カンムリ",firstNameKana:" ミヨシ",sex: 1},
  { name:"廣末 一恵",nameKana:"ヒロスエ  イチエ",lastName:"廣末",firstName:"一恵",lastNameKana:"ヒロスエ",firstNameKana:" イチエ",sex: 1},
  { name:"塩濱 ハル",nameKana:"シオハマ マ ハル",lastName:"塩濱",firstName:"ハル",lastNameKana:"シオハマ",firstNameKana:"マ ハル",sex: 1},
  { name:"三方 ひさこ",nameKana:"ミカタ ヒサコ",lastName:"三方",firstName:"さこ",lastNameKana:"ミカタ",firstNameKana:"ヒサコ",sex: 1},
  { name:"松方 由紀代",nameKana:"マツカタ  ユキヨ",lastName:"松方",firstName:"紀代",lastNameKana:"マツカタ",firstNameKana:" ユキヨ",sex: 1},
  { name:"長柄 惟子",nameKana:"ナガラ ユイコ",lastName:"長柄",firstName:"惟子",lastNameKana:"ナガラ",firstNameKana:"ユイコ",sex: 1},
  { name:"轡田 優羽",nameKana:"クツワダ ダ ユウ",lastName:"轡田",firstName:"優羽",lastNameKana:"クツワダ",firstNameKana:"ダ ユウ",sex: 1},
  { name:"観月 佳容子",nameKana:"ミヅキ カヨコ",lastName:"観月",firstName:"容子",lastNameKana:"ミヅキ",firstNameKana:"カヨコ",sex: 1},
  { name:"戸根 滋美",nameKana:"トネ ゲミ",lastName:"戸根",firstName:"滋美",lastNameKana:"トネ",firstNameKana:"ゲミ",sex: 1},
  { name:"新里 悠乃",nameKana:"ニイザト  ユウノ",lastName:"新里",firstName:"悠乃",lastNameKana:"ニイザト",firstNameKana:" ユウノ",sex: 1},
  { name:"茂庭 ふゆみ",nameKana:"モニワ フユミ",lastName:"茂庭",firstName:"ゆみ",lastNameKana:"モニワ",firstNameKana:"フユミ",sex: 1},
  { name:"矢戸 佐世",nameKana:"ヤト サヨ",lastName:"矢戸",firstName:"佐世",lastNameKana:"ヤト",firstNameKana:"サヨ",sex: 1},
  { name:"市位 日香留",nameKana:"イチイ ヒカル",lastName:"市位",firstName:"香留",lastNameKana:"イチイ",firstNameKana:"ヒカル",sex: 1},
  { name:"横島 サトミ",nameKana:"ヨコジマ  サトミ",lastName:"横島",firstName:"トミ",lastNameKana:"ヨコジマ",firstNameKana:" サトミ",sex: 1},
  { name:"江西 展子",nameKana:"エニシ ノリコ",lastName:"江西",firstName:"展子",lastNameKana:"エニシ",firstNameKana:"ノリコ",sex: 1},
  { name:"赤井田 香純",nameKana:"アカイダ  カズミ",lastName:"赤井田",firstName:" 香純",lastNameKana:"アカイダ",firstNameKana:" カズミ",sex: 1},
  { name:"延山 時江",nameKana:"ノブヤマ  トキエ",lastName:"延山",firstName:"時江",lastNameKana:"ノブヤマ",firstNameKana:" トキエ",sex: 1},
  { name:"荻野目 由美佳",nameKana:"オギノメ  ユミカ",lastName:"荻野目",firstName:"由美佳",lastNameKana:"オギノメ",firstNameKana:" ユミカ",sex: 1},
  { name:"兼頭 愛里菜",nameKana:"カネトウ  エリナ",lastName:"兼頭",firstName:"里菜",lastNameKana:"カネトウ",firstNameKana:" エリナ",sex: 1},
  { name:"仲光 雅予",nameKana:"ナカミツ  マサヨ",lastName:"仲光",firstName:"雅予",lastNameKana:"ナカミツ",firstNameKana:" マサヨ",sex: 1},
  { name:"矢留 沙枝子",nameKana:"ヤトメ サエコ",lastName:"矢留",firstName:"枝子",lastNameKana:"ヤトメ",firstNameKana:"サエコ",sex: 1},
  { name:"大洞 可奈江",nameKana:"オオホラ  カナエ",lastName:"大洞",firstName:"奈江",lastNameKana:"オオホラ",firstNameKana:" カナエ",sex: 1},
  { name:"魚津 優妃",nameKana:"ウオヅ ユウヒ",lastName:"魚津",firstName:"優妃",lastNameKana:"ウオヅ",firstNameKana:"ユウヒ",sex: 1},
  { name:"北室 江吏子",nameKana:"キタムロ  エリコ",lastName:"北室",firstName:"吏子",lastNameKana:"キタムロ",firstNameKana:" エリコ",sex: 1},
  { name:"原之園 悠梨",nameKana:"ハラノソノ ソノ ユリ",lastName:"原之園",firstName:" 悠梨",lastNameKana:"ハラノソノ",firstNameKana:"ソノ ユリ",sex: 1},
  { name:"釘抜 永実",nameKana:"クギヌキ キ エミ",lastName:"釘抜",firstName:"永実",lastNameKana:"クギヌキ",firstNameKana:"キ エミ",sex: 1},
  { name:"是近 昭枝",nameKana:"コレチカ  アキエ",lastName:"是近",firstName:"昭枝",lastNameKana:"コレチカ",firstNameKana:" アキエ",sex: 1},
  { name:"和佐野 恵未子",nameKana:"ワサノ エミコ",lastName:"和佐野",firstName:"恵未子",lastNameKana:"ワサノ",firstNameKana:"エミコ",sex: 1},
  { name:"吉正 由菜",nameKana:"ヨシマサ  ユイナ",lastName:"吉正",firstName:"由菜",lastNameKana:"ヨシマサ",firstNameKana:" ユイナ",sex: 1},
  { name:"稲邑 桂代",nameKana:"イナムラ ラ カヨ",lastName:"稲邑",firstName:"桂代",lastNameKana:"イナムラ",firstNameKana:"ラ カヨ",sex: 1},
  { name:"朽名 佐起",nameKana:"クツナ  サキ",lastName:"朽名",firstName:"佐起",lastNameKana:"クツナ",firstNameKana:" サキ",sex: 1},
  { name:"小井沼 恵奈",nameKana:"コイヌマ  アヤナ",lastName:"小井沼",firstName:" 恵奈",lastNameKana:"コイヌマ",firstNameKana:" アヤナ",sex: 1},
  { name:"下御領 友嘉",nameKana:"シモゴリョウ リョウ ユカ",lastName:"下御領",firstName:" 友嘉",lastNameKana:"シモゴリョウ",firstNameKana:"リョウ ユカ",sex: 1},
  { name:"二重 沙千子",nameKana:"ニガラ サチコ",lastName:"二重",firstName:"千子",lastNameKana:"ニガラ",firstNameKana:"サチコ",sex: 1},
  { name:"六馬 菜々枝",nameKana:"ロクウマ  ナナエ",lastName:"六馬",firstName:"々枝",lastNameKana:"ロクウマ",firstNameKana:" ナナエ",sex: 1},
  { name:"西花 歩",nameKana:"ニシハナ ナ アユ",lastName:"西花",firstName:" 歩",lastNameKana:"ニシハナ",firstNameKana:"ナ アユ",sex: 1},
  { name:"中山 真利枝",nameKana:"ナカマヤ  マリエ",lastName:"中山",firstName:"利枝",lastNameKana:"ナカマヤ",firstNameKana:" マリエ",sex: 1},
  { name:"岸間 茉莉那",nameKana:"ガンマ マリナ",lastName:"岸間",firstName:"莉那",lastNameKana:"ガンマ",firstNameKana:"マリナ",sex: 1},
  { name:"真謝 幾恵",nameKana:"マジャ イクエ",lastName:"真謝",firstName:"幾恵",lastNameKana:"マジャ",firstNameKana:"イクエ",sex: 1},
  { name:"漠 芹佳",nameKana:"バク リカ",lastName:"漠",firstName:"佳",lastNameKana:"バク",firstNameKana:"リカ",sex: 1},
  { name:"細居 靖佳",nameKana:"ホソイ ヤスカ",lastName:"細居",firstName:"靖佳",lastNameKana:"ホソイ",firstNameKana:"ヤスカ",sex: 1},
  { name:"丸二 香菜枝",nameKana:"マルニ カナエ",lastName:"丸二",firstName:"菜枝",lastNameKana:"マルニ",firstNameKana:"カナエ",sex: 1},
  { name:"羽場崎 奈美代",nameKana:"ハバザキ  ナミヨ",lastName:"羽場崎",firstName:"奈美代",lastNameKana:"ハバザキ",firstNameKana:" ナミヨ",sex: 1},
  { name:"植付 朱紀",nameKana:"ウエツケ ケ アキ",lastName:"植付",firstName:"朱紀",lastNameKana:"ウエツケ",firstNameKana:"ケ アキ",sex: 1},
  { name:"一ノ口 左代子",nameKana:"イチノクチ チ サヨコ",lastName:"一ノ口",firstName:"左代子",lastNameKana:"イチノクチ",firstNameKana:"チ サヨコ",sex: 1},
  { name:"蓮谷 都萌",nameKana:"ハスタニ  トモエ",lastName:"蓮谷",firstName:"都萌",lastNameKana:"ハスタニ",firstNameKana:" トモエ",sex: 1},
];
