const names = [
  { name:"澁谷 信也",nameKana:"シブヤ シンヤ",firstName:"澁谷",lastName:"信也",firstNameKana:"シブヤ",lastNameKana:"シンヤ",sex: 0},
  { name:"駒井 智",nameKana:"コマイ サトル",firstName:"駒井",lastName:" 智",firstNameKana:"コマイ",lastNameKana:"サトル",sex: 0},
  { name:"高塚 崇史",nameKana:"タカツカ  タカシ",firstName:"高塚",lastName:"崇史",firstNameKana:"タカツカ",lastNameKana:" タカシ",sex: 0},
  { name:"弘田 正文",nameKana:"ヒロタ サフミ",firstName:"弘田",lastName:"正文",firstNameKana:"ヒロタ",lastNameKana:"サフミ",sex: 0},
  { name:"田北 秀則",nameKana:"タキタ デノリ",firstName:"田北",lastName:"秀則",firstNameKana:"タキタ",lastNameKana:"デノリ",sex: 0},
  { name:"池畑 昌明",nameKana:"イケハタ マサアキ",firstName:"池畑",lastName:"昌明",firstNameKana:"イケハタ",lastNameKana:"マサアキ",sex: 0},
  { name:"鷲田 至",nameKana:"ワシダ イタル",firstName:"鷲田",lastName:" 至",firstNameKana:"ワシダ",lastNameKana:"イタル",sex: 0},
  { name:"五十川 文昭",nameKana:"イソガワ フミアキ",firstName:"五十川",lastName:" 文昭",firstNameKana:"イソガワ",lastNameKana:"フミアキ",sex: 0},
  { name:"洞口 一生",nameKana:"ホラグチ  カズオ",firstName:"洞口",lastName:"一生",firstNameKana:"ホラグチ",lastNameKana:" カズオ",sex: 0},
  { name:"坂爪 雅巳",nameKana:"サカヅメ  マサミ",firstName:"坂爪",lastName:"雅巳",firstNameKana:"サカヅメ",lastNameKana:" マサミ",sex: 0},
  { name:"徳富 善博",nameKana:"トクトミ ヨシヒロ",firstName:"徳富",lastName:"善博",firstNameKana:"トクトミ",lastNameKana:"ヨシヒロ",sex: 0},
  { name:"横村 広宣",nameKana:"ヨコムラ ヒロノブ",firstName:"横村",lastName:"広宣",firstNameKana:"ヨコムラ",lastNameKana:"ヒロノブ",sex: 0},
  { name:"常田 晴雄",nameKana:"ツネダ ハルオ",firstName:"常田",lastName:"晴雄",firstNameKana:"ツネダ",lastNameKana:"ハルオ",sex: 0},
  { name:"種本 正士",nameKana:"タネモト  マサシ",firstName:"種本",lastName:"正士",firstNameKana:"タネモト",lastNameKana:" マサシ",sex: 0},
  { name:"湊谷 浩志",nameKana:"ミナトヤ  コウジ",firstName:"湊谷",lastName:"浩志",firstNameKana:"ミナトヤ",lastNameKana:" コウジ",sex: 0},
  { name:"岡垣 雅嗣",nameKana:"オカガキ マサツグ",firstName:"岡垣",lastName:"雅嗣",firstNameKana:"オカガキ",lastNameKana:"マサツグ",sex: 0},
  { name:"依藤 昌大",nameKana:"ヨリフジ マサヒロ",firstName:"依藤",lastName:"昌大",firstNameKana:"ヨリフジ",lastNameKana:"マサヒロ",sex: 0},
  { name:"前澤 慧太",nameKana:"マエサワ  ケイタ",firstName:"前澤",lastName:"慧太",firstNameKana:"マエサワ",lastNameKana:" ケイタ",sex: 0},
  { name:"内林 大将",nameKana:"ウチバヤシ  ヒロマサ",firstName:"内林",lastName:"大将",firstNameKana:"ウチバヤシ",lastNameKana:" ヒロマサ",sex: 0},
  { name:"稲野辺 功一郎",nameKana:"イナノベ イチロウ",firstName:"稲野辺",lastName:"功一郎",firstNameKana:"イナノベ",lastNameKana:"イチロウ",sex: 0},
  { name:"桂 正泰",nameKana:"ケイ ヤス",firstName:"桂",lastName:"泰",firstNameKana:"ケイ",lastNameKana:"ヤス",sex: 0},
  { name:"野並 健二朗",nameKana:"ノナミ ジロウ",firstName:"野並",lastName:"二朗",firstNameKana:"ノナミ",lastNameKana:"ジロウ",sex: 0},
  { name:"宮重 眞澄",nameKana:"ミヤシゲ  マスミ",firstName:"宮重",lastName:"眞澄",firstNameKana:"ミヤシゲ",lastNameKana:" マスミ",sex: 0},
  { name:"島原 茂弘",nameKana:"シマバラ シゲヒロ",firstName:"島原",lastName:"茂弘",firstNameKana:"シマバラ",lastNameKana:"シゲヒロ",sex: 0},
  { name:"戦 將人",nameKana:"セン サト",firstName:"戦",lastName:"人",firstNameKana:"セン",lastNameKana:"サト",sex: 0},
  { name:"玄番 政洋",nameKana:"ゲンバ サヒロ",firstName:"玄番",lastName:"政洋",firstNameKana:"ゲンバ",lastNameKana:"サヒロ",sex: 0},
  { name:"向谷 大裕",nameKana:"ムカイダニ  ダイスケ",firstName:"向谷",lastName:"大裕",firstNameKana:"ムカイダニ",lastNameKana:" ダイスケ",sex: 0},
  { name:"宇土 龍三",nameKana:"ウド ゾウ",firstName:"宇土",lastName:"龍三",firstNameKana:"ウド",lastNameKana:"ゾウ",sex: 0},
  { name:"福王寺 益弘",nameKana:"フクオウジ  マスヒロ",firstName:"福王寺",lastName:" 益弘",firstNameKana:"フクオウジ",lastNameKana:" マスヒロ",sex: 0},
  { name:"矢埜 滉太",nameKana:"ヤノ ウタ",firstName:"矢埜",lastName:"滉太",firstNameKana:"ヤノ",lastNameKana:"ウタ",sex: 0},
  { name:"小野塚 淳史",nameKana:"オノツカ ジュンジ",firstName:"小野塚",lastName:" 淳史",firstNameKana:"オノツカ",lastNameKana:"ジュンジ",sex: 0},
  { name:"掛布 喜幸",nameKana:"カケノ シユキ",firstName:"掛布",lastName:"喜幸",firstNameKana:"カケノ",lastNameKana:"シユキ",sex: 0},
  { name:"夏苅 連",nameKana:"ナツガリ リ レン",firstName:"夏苅",lastName:" 連",firstNameKana:"ナツガリ",lastNameKana:"リ レン",sex: 0},
  { name:"舛谷 恒一郎",nameKana:"マスタニ イチロウ",firstName:"舛谷",lastName:"一郎",firstNameKana:"マスタニ",lastNameKana:"イチロウ",sex: 0},
  { name:"伊良原 剣",nameKana:"イラハラ  ツルギ",firstName:"伊良原",lastName:"原 剣",firstNameKana:"イラハラ",lastNameKana:" ツルギ",sex: 0},
  { name:"天明 穣二",nameKana:"テンメイ ジョウジ",firstName:"天明",lastName:"穣二",firstNameKana:"テンメイ",lastNameKana:"ジョウジ",sex: 0},
  { name:"埴田 秀策",nameKana:"ハニダ ウサク",firstName:"埴田",lastName:"秀策",firstNameKana:"ハニダ",lastNameKana:"ウサク",sex: 0},
  { name:"諸我 奨",nameKana:"モロガ タスク",firstName:"諸我",lastName:" 奨",firstNameKana:"モロガ",lastNameKana:"タスク",sex: 0},
  { name:"棈木 雄市",nameKana:"アベキ ウイチ",firstName:"棈木",lastName:"雄市",firstNameKana:"アベキ",lastNameKana:"ウイチ",sex: 0},
  { name:"日川 佳人",nameKana:"ヒカワ ヨシト",firstName:"日川",lastName:"佳人",firstNameKana:"ヒカワ",lastNameKana:"ヨシト",sex: 0},
  { name:"坂宮 研悟",nameKana:"サカミヤ  ケンゴ",firstName:"坂宮",lastName:"研悟",firstNameKana:"サカミヤ",lastNameKana:" ケンゴ",sex: 0},
  { name:"溝添 国弘",nameKana:"ミゾゾエ クニヒロ",firstName:"溝添",lastName:"国弘",firstNameKana:"ミゾゾエ",lastNameKana:"クニヒロ",sex: 0},
  { name:"葭田 靖成",nameKana:"ヨシタ スナリ",firstName:"葭田",lastName:"靖成",firstNameKana:"ヨシタ",lastNameKana:"スナリ",sex: 0},
  { name:"新乃 勝吉",nameKana:"シンノ ツヨシ",firstName:"新乃",lastName:"勝吉",firstNameKana:"シンノ",lastNameKana:"ツヨシ",sex: 0},
  { name:"小勝負 研史",nameKana:"コショウブ ブ ケンジ",firstName:"小勝負",lastName:" 研史",firstNameKana:"コショウブ",lastNameKana:"ブ ケンジ",sex: 0},
  { name:"髙岩 崇志",nameKana:"タカイワ タカユキ",firstName:"髙岩",lastName:"崇志",firstNameKana:"タカイワ",lastNameKana:"タカユキ",sex: 0},
  { name:"増毛 秀克",nameKana:"マスモ デカツ",firstName:"増毛",lastName:"秀克",firstNameKana:"マスモ",lastNameKana:"デカツ",sex: 0},
  { name:"黒堀 光祥",nameKana:"クロホリ ミツヨシ",firstName:"黒堀",lastName:"光祥",firstNameKana:"クロホリ",lastNameKana:"ミツヨシ",sex: 0},
  { name:"駄木 知克",nameKana:"ダキ カツ",firstName:"駄木",lastName:"知克",firstNameKana:"ダキ",lastNameKana:"カツ",sex: 0},
  { name:"髑髏林 剛士",nameKana:"ドクロバヤシ ヤシ ゴウシ",firstName:"髑髏林",lastName:" 剛士",firstNameKana:"ドクロバヤシ",lastNameKana:"ヤシ ゴウシ",sex: 0},
  { name:"小鴨 黒",nameKana:"コガモ  クロ",firstName:"小鴨",lastName:" 黒",firstNameKana:"コガモ",lastNameKana:" クロ",sex: 0},
  { name:"丹慶 広孝",nameKana:"タンケイ ヒロタカ",firstName:"丹慶",lastName:"広孝",firstNameKana:"タンケイ",lastNameKana:"ヒロタカ",sex: 0},
  { name:"宅瀬 学人",nameKana:"タクセ マナト",firstName:"宅瀬",lastName:"学人",firstNameKana:"タクセ",lastNameKana:"マナト",sex: 0},
  { name:"奈津 長門",nameKana:"ナツ ガト",firstName:"奈津",lastName:"長門",firstNameKana:"ナツ",lastNameKana:"ガト",sex: 0},
  { name:"入梅 倫正",nameKana:"イリウメ ミチマサ",firstName:"入梅",lastName:"倫正",firstNameKana:"イリウメ",lastNameKana:"ミチマサ",sex: 0},
  { name:"白根澤 信基",nameKana:"シラネザワ ワ ノブキ",firstName:"白根澤",lastName:" 信基",firstNameKana:"シラネザワ",lastNameKana:"ワ ノブキ",sex: 0},
  { name:"新改 恵理也",nameKana:"シンガイ  エリヤ",firstName:"新改",lastName:"理也",firstNameKana:"シンガイ",lastNameKana:" エリヤ",sex: 0},
  { name:"崎花 崇成",nameKana:"サキハナ タカナリ",firstName:"崎花",lastName:"崇成",firstNameKana:"サキハナ",lastNameKana:"タカナリ",sex: 0},
  { name:"湯倉 永悟",nameKana:"ユクラ エイゴ",firstName:"湯倉",lastName:"永悟",firstNameKana:"ユクラ",lastNameKana:"エイゴ",sex: 0},
  { name:"家治川 巡",nameKana:"カジカワ  メグル",firstName:"家治川",lastName:"川 巡",firstNameKana:"カジカワ",lastNameKana:" メグル",sex: 0},
  { name:"本多 真由",nameKana:"ホンダ  マユ",firstName:"本多",lastName:"真由",firstNameKana:"ホンダ",lastNameKana:" マユ",sex: 1},
  { name:"藤沢 優香",nameKana:"フジサワ  ユウカ",firstName:"藤沢",lastName:"優香",firstNameKana:"フジサワ",lastNameKana:" ユウカ",sex: 1},
  { name:"古井 昭子",nameKana:"フルイ アキコ",firstName:"古井",lastName:"昭子",firstNameKana:"フルイ",lastNameKana:"アキコ",sex: 1},
  { name:"小濱 歩実",nameKana:"コハマ アユミ",firstName:"小濱",lastName:"歩実",firstNameKana:"コハマ",lastNameKana:"アユミ",sex: 1},
  { name:"江森 政子",nameKana:"エモリ マサコ",firstName:"江森",lastName:"政子",firstNameKana:"エモリ",lastNameKana:"マサコ",sex: 1},
  { name:"白倉 千智",nameKana:"シラクラ  チサト",firstName:"白倉",lastName:"千智",firstNameKana:"シラクラ",lastNameKana:" チサト",sex: 1},
  { name:"茂木 紗央里",nameKana:"モテキ サオリ",firstName:"茂木",lastName:"央里",firstNameKana:"モテキ",lastNameKana:"サオリ",sex: 1},
  { name:"牧村 和香奈",nameKana:"マキムラ  ワカナ",firstName:"牧村",lastName:"香奈",firstNameKana:"マキムラ",lastNameKana:" ワカナ",sex: 1},
  { name:"伊崎 栄",nameKana:"イザキ サカエ",firstName:"伊崎",lastName:" 栄",firstNameKana:"イザキ",lastNameKana:"サカエ",sex: 1},
  { name:"岩脇 朋枝",nameKana:"イワワキ  トモエ",firstName:"岩脇",lastName:"朋枝",firstNameKana:"イワワキ",lastNameKana:" トモエ",sex: 1},
  { name:"天木 早代",nameKana:"アマキ  サヨ",firstName:"天木",lastName:"早代",firstNameKana:"アマキ",lastNameKana:" サヨ",sex: 1},
  { name:"古泉 涼香",nameKana:"コイズミ リョウカ",firstName:"古泉",lastName:"涼香",firstNameKana:"コイズミ",lastNameKana:"リョウカ",sex: 1},
  { name:"中司 カナ",nameKana:"ナカツカサ カサ カナ",firstName:"中司",lastName:"カナ",firstNameKana:"ナカツカサ",lastNameKana:"カサ カナ",sex: 1},
  { name:"高阪 きよ子",nameKana:"コウサカ  キヨコ",firstName:"高阪",lastName:"よ子",firstNameKana:"コウサカ",lastNameKana:" キヨコ",sex: 1},
  { name:"冠 美好",nameKana:"カンムリ  ミヨシ",firstName:"冠",lastName:"好",firstNameKana:"カンムリ",lastNameKana:" ミヨシ",sex: 1},
  { name:"廣末 一恵",nameKana:"ヒロスエ  イチエ",firstName:"廣末",lastName:"一恵",firstNameKana:"ヒロスエ",lastNameKana:" イチエ",sex: 1},
  { name:"塩濱 ハル",nameKana:"シオハマ マ ハル",firstName:"塩濱",lastName:"ハル",firstNameKana:"シオハマ",lastNameKana:"マ ハル",sex: 1},
  { name:"三方 ひさこ",nameKana:"ミカタ ヒサコ",firstName:"三方",lastName:"さこ",firstNameKana:"ミカタ",lastNameKana:"ヒサコ",sex: 1},
  { name:"松方 由紀代",nameKana:"マツカタ  ユキヨ",firstName:"松方",lastName:"紀代",firstNameKana:"マツカタ",lastNameKana:" ユキヨ",sex: 1},
  { name:"長柄 惟子",nameKana:"ナガラ ユイコ",firstName:"長柄",lastName:"惟子",firstNameKana:"ナガラ",lastNameKana:"ユイコ",sex: 1},
  { name:"轡田 優羽",nameKana:"クツワダ ダ ユウ",firstName:"轡田",lastName:"優羽",firstNameKana:"クツワダ",lastNameKana:"ダ ユウ",sex: 1},
  { name:"観月 佳容子",nameKana:"ミヅキ カヨコ",firstName:"観月",lastName:"容子",firstNameKana:"ミヅキ",lastNameKana:"カヨコ",sex: 1},
  { name:"戸根 滋美",nameKana:"トネ ゲミ",firstName:"戸根",lastName:"滋美",firstNameKana:"トネ",lastNameKana:"ゲミ",sex: 1},
  { name:"新里 悠乃",nameKana:"ニイザト  ユウノ",firstName:"新里",lastName:"悠乃",firstNameKana:"ニイザト",lastNameKana:" ユウノ",sex: 1},
  { name:"茂庭 ふゆみ",nameKana:"モニワ フユミ",firstName:"茂庭",lastName:"ゆみ",firstNameKana:"モニワ",lastNameKana:"フユミ",sex: 1},
  { name:"矢戸 佐世",nameKana:"ヤト サヨ",firstName:"矢戸",lastName:"佐世",firstNameKana:"ヤト",lastNameKana:"サヨ",sex: 1},
  { name:"市位 日香留",nameKana:"イチイ ヒカル",firstName:"市位",lastName:"香留",firstNameKana:"イチイ",lastNameKana:"ヒカル",sex: 1},
  { name:"横島 サトミ",nameKana:"ヨコジマ  サトミ",firstName:"横島",lastName:"トミ",firstNameKana:"ヨコジマ",lastNameKana:" サトミ",sex: 1},
  { name:"江西 展子",nameKana:"エニシ ノリコ",firstName:"江西",lastName:"展子",firstNameKana:"エニシ",lastNameKana:"ノリコ",sex: 1},
  { name:"赤井田 香純",nameKana:"アカイダ  カズミ",firstName:"赤井田",lastName:" 香純",firstNameKana:"アカイダ",lastNameKana:" カズミ",sex: 1},
  { name:"延山 時江",nameKana:"ノブヤマ  トキエ",firstName:"延山",lastName:"時江",firstNameKana:"ノブヤマ",lastNameKana:" トキエ",sex: 1},
  { name:"荻野目 由美佳",nameKana:"オギノメ  ユミカ",firstName:"荻野目",lastName:"由美佳",firstNameKana:"オギノメ",lastNameKana:" ユミカ",sex: 1},
  { name:"兼頭 愛里菜",nameKana:"カネトウ  エリナ",firstName:"兼頭",lastName:"里菜",firstNameKana:"カネトウ",lastNameKana:" エリナ",sex: 1},
  { name:"仲光 雅予",nameKana:"ナカミツ  マサヨ",firstName:"仲光",lastName:"雅予",firstNameKana:"ナカミツ",lastNameKana:" マサヨ",sex: 1},
  { name:"矢留 沙枝子",nameKana:"ヤトメ サエコ",firstName:"矢留",lastName:"枝子",firstNameKana:"ヤトメ",lastNameKana:"サエコ",sex: 1},
  { name:"大洞 可奈江",nameKana:"オオホラ  カナエ",firstName:"大洞",lastName:"奈江",firstNameKana:"オオホラ",lastNameKana:" カナエ",sex: 1},
  { name:"魚津 優妃",nameKana:"ウオヅ ユウヒ",firstName:"魚津",lastName:"優妃",firstNameKana:"ウオヅ",lastNameKana:"ユウヒ",sex: 1},
  { name:"北室 江吏子",nameKana:"キタムロ  エリコ",firstName:"北室",lastName:"吏子",firstNameKana:"キタムロ",lastNameKana:" エリコ",sex: 1},
  { name:"原之園 悠梨",nameKana:"ハラノソノ ソノ ユリ",firstName:"原之園",lastName:" 悠梨",firstNameKana:"ハラノソノ",lastNameKana:"ソノ ユリ",sex: 1},
  { name:"釘抜 永実",nameKana:"クギヌキ キ エミ",firstName:"釘抜",lastName:"永実",firstNameKana:"クギヌキ",lastNameKana:"キ エミ",sex: 1},
  { name:"是近 昭枝",nameKana:"コレチカ  アキエ",firstName:"是近",lastName:"昭枝",firstNameKana:"コレチカ",lastNameKana:" アキエ",sex: 1},
  { name:"和佐野 恵未子",nameKana:"ワサノ エミコ",firstName:"和佐野",lastName:"恵未子",firstNameKana:"ワサノ",lastNameKana:"エミコ",sex: 1},
  { name:"吉正 由菜",nameKana:"ヨシマサ  ユイナ",firstName:"吉正",lastName:"由菜",firstNameKana:"ヨシマサ",lastNameKana:" ユイナ",sex: 1},
  { name:"稲邑 桂代",nameKana:"イナムラ ラ カヨ",firstName:"稲邑",lastName:"桂代",firstNameKana:"イナムラ",lastNameKana:"ラ カヨ",sex: 1},
  { name:"朽名 佐起",nameKana:"クツナ  サキ",firstName:"朽名",lastName:"佐起",firstNameKana:"クツナ",lastNameKana:" サキ",sex: 1},
  { name:"小井沼 恵奈",nameKana:"コイヌマ  アヤナ",firstName:"小井沼",lastName:" 恵奈",firstNameKana:"コイヌマ",lastNameKana:" アヤナ",sex: 1},
  { name:"下御領 友嘉",nameKana:"シモゴリョウ リョウ ユカ",firstName:"下御領",lastName:" 友嘉",firstNameKana:"シモゴリョウ",lastNameKana:"リョウ ユカ",sex: 1},
  { name:"二重 沙千子",nameKana:"ニガラ サチコ",firstName:"二重",lastName:"千子",firstNameKana:"ニガラ",lastNameKana:"サチコ",sex: 1},
  { name:"六馬 菜々枝",nameKana:"ロクウマ  ナナエ",firstName:"六馬",lastName:"々枝",firstNameKana:"ロクウマ",lastNameKana:" ナナエ",sex: 1},
  { name:"西花 歩",nameKana:"ニシハナ ナ アユ",firstName:"西花",lastName:" 歩",firstNameKana:"ニシハナ",lastNameKana:"ナ アユ",sex: 1},
  { name:"中山 真利枝",nameKana:"ナカマヤ  マリエ",firstName:"中山",lastName:"利枝",firstNameKana:"ナカマヤ",lastNameKana:" マリエ",sex: 1},
  { name:"岸間 茉莉那",nameKana:"ガンマ マリナ",firstName:"岸間",lastName:"莉那",firstNameKana:"ガンマ",lastNameKana:"マリナ",sex: 1},
  { name:"真謝 幾恵",nameKana:"マジャ イクエ",firstName:"真謝",lastName:"幾恵",firstNameKana:"マジャ",lastNameKana:"イクエ",sex: 1},
  { name:"漠 芹佳",nameKana:"バク リカ",firstName:"漠",lastName:"佳",firstNameKana:"バク",lastNameKana:"リカ",sex: 1},
  { name:"細居 靖佳",nameKana:"ホソイ ヤスカ",firstName:"細居",lastName:"靖佳",firstNameKana:"ホソイ",lastNameKana:"ヤスカ",sex: 1},
  { name:"丸二 香菜枝",nameKana:"マルニ カナエ",firstName:"丸二",lastName:"菜枝",firstNameKana:"マルニ",lastNameKana:"カナエ",sex: 1},
  { name:"羽場崎 奈美代",nameKana:"ハバザキ  ナミヨ",firstName:"羽場崎",lastName:"奈美代",firstNameKana:"ハバザキ",lastNameKana:" ナミヨ",sex: 1},
  { name:"植付 朱紀",nameKana:"ウエツケ ケ アキ",firstName:"植付",lastName:"朱紀",firstNameKana:"ウエツケ",lastNameKana:"ケ アキ",sex: 1},
  { name:"一ノ口 左代子",nameKana:"イチノクチ チ サヨコ",firstName:"一ノ口",lastName:"左代子",firstNameKana:"イチノクチ",lastNameKana:"チ サヨコ",sex: 1},
  { name:"蓮谷 都萌",nameKana:"ハスタニ  トモエ",firstName:"蓮谷",lastName:"都萌",firstNameKana:"ハスタニ",lastNameKana:" トモエ",sex: 1},
];

module.exports = names;